"""Unit tests for E2's D-15/D-16 invocation-config generator and its honest
`--check` verdict (Phase 26 plan 26-06).

Two surfaces are covered:

1. `build_internals_variant_config` / `emit_invocation_configs` -- the pure
   text-to-text `internals.*` override transform and the three-variant emitter
   that makes E2's classification / timing / memory invocations distinct
   (D-15: `internals.benchmark_memory` costs 2.7-5.5% wall clock, so one run
   cannot honestly produce both the timing and the memory number; D-16:
   `internals.log_all_observation_depths` writes an ~11 MB per-stage sidecar
   and therefore rides the classification run only).
2. `_fold_check_reports` -- E2's `--check` verdict folding, where a baseline
   gitignored by DATA-01b policy is an N/A rather than a crash (ruling A4),
   but an all-N/A check is never a pass.

Every test uses a small inline fixture config -- never the real Desktop
production config -- so the suite has no external dependency and never touches
`C:/Users/tucke/Desktop/Aqua/AquaCal/release_calibration/`. **No test here
invokes `run_calibration` or performs a calibration**: one E2 run is 48-87
minutes and needs a 4.35 GB frameset.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest
import yaml

from experiments._io import ComparisonReport
from experiments.e2_real_rig import (
    E2_INVOCATION_VARIANTS,
    _fold_check_reports,
    build_arg_parser,
    build_internals_variant_config,
    emit_invocation_configs,
    main,
)

# A fixture config carrying comments, blank lines, a nested `paths:` block and
# a full `internals:` block -- the shape of the real production config without
# any real paths.
FIXTURE_CONFIG = """\
# AquaCal configuration file
# Generated by 'aquacal init'

board:
  squares_x: 12
  squares_y: 9

cameras:
  - cam0
  - cam1

paths:
  extrinsic_videos:
    cam0: "/videos/extrinsics/cam0.avi"
  output_dir: "/original/output_dir"

internals:
  save_benchmark: true
  benchmark_memory: false  # Opt-in: per-stage peak RSS
  log_all_observation_depths: false
  seed: 42

interface:
  n_air: 1.0
  n_water: 1.333
"""

# Same config, but with neither override key present inside `internals:`.
FIXTURE_CONFIG_PARTIAL_INTERNALS = """\
# AquaCal configuration file

paths:
  output_dir: "/original/output_dir"

internals:
  save_benchmark: true
  seed: 42
"""

# Same config with no `internals:` block at all.
FIXTURE_CONFIG_NO_INTERNALS = """\
# AquaCal configuration file

paths:
  output_dir: "/original/output_dir"

interface:
  n_air: 1.0
"""


def _write_source(tmp_path: Path, text: str = FIXTURE_CONFIG) -> Path:
    """Write a fixture config into an isolated 'release tree' directory."""
    release_dir = tmp_path / "release_calibration"
    release_dir.mkdir(parents=True, exist_ok=True)
    source = release_dir / "config.yaml"
    source.write_text(text)
    return source


def _changed_line_indices(before: str, after: str) -> list[int]:
    """Indices of lines that differ between two same-length texts."""
    a = before.splitlines()
    b = after.splitlines()
    assert len(a) == len(b), "line count changed; no in-place transform"
    return [i for i, (x, y) in enumerate(zip(a, b)) if x != y]


# ---------------------------------------------------------------------------
# Task 1: build_internals_variant_config
# ---------------------------------------------------------------------------


def test_changes_exactly_one_plus_len_overrides_lines_when_keys_preexist():
    overrides = {"benchmark_memory": True, "log_all_observation_depths": False}
    result = build_internals_variant_config(
        FIXTURE_CONFIG, "/new/output_dir", overrides
    )
    changed = _changed_line_indices(FIXTURE_CONFIG, result)
    assert len(changed) == 1 + len(overrides)


def test_every_comment_and_unrelated_line_survives_byte_for_byte():
    result = build_internals_variant_config(
        FIXTURE_CONFIG, "/new/output_dir", {"benchmark_memory": True}
    )
    for line in (
        "# AquaCal configuration file",
        "# Generated by 'aquacal init'",
        "  squares_x: 12",
        "  - cam1",
        '    cam0: "/videos/extrinsics/cam0.avi"',
        "  save_benchmark: true",
        "  seed: 42",
        "  n_water: 1.333",
    ):
        assert line in result.splitlines()


def test_rewrites_output_dir_and_override_values():
    result = build_internals_variant_config(
        FIXTURE_CONFIG,
        "/new/output_dir",
        {"benchmark_memory": True, "log_all_observation_depths": False},
    )
    loaded = yaml.safe_load(result)
    assert loaded["paths"]["output_dir"] == "/new/output_dir"
    assert loaded["internals"]["benchmark_memory"] is True
    assert loaded["internals"]["log_all_observation_depths"] is False
    # Untouched neighbours keep their values.
    assert loaded["internals"]["save_benchmark"] is True
    assert loaded["internals"]["seed"] == 42


def test_inserts_missing_key_into_existing_internals_block():
    result = build_internals_variant_config(
        FIXTURE_CONFIG_PARTIAL_INTERNALS,
        "/new/output_dir",
        {"benchmark_memory": True, "log_all_observation_depths": True},
    )
    loaded = yaml.safe_load(result)
    assert loaded["internals"]["benchmark_memory"] is True
    assert loaded["internals"]["log_all_observation_depths"] is True
    assert loaded["internals"]["save_benchmark"] is True
    assert loaded["paths"]["output_dir"] == "/new/output_dir"


def test_creates_internals_block_when_absent():
    result = build_internals_variant_config(
        FIXTURE_CONFIG_NO_INTERNALS,
        "/new/output_dir",
        {"benchmark_memory": True},
    )
    loaded = yaml.safe_load(result)
    assert loaded["internals"]["benchmark_memory"] is True
    assert loaded["interface"]["n_air"] == 1.0
    assert "internals:" in result


def test_raises_when_no_output_dir_line_to_rewrite():
    with pytest.raises(ValueError, match="output_dir"):
        build_internals_variant_config(
            "board:\n  squares_x: 12\n", "/new/output_dir", {"benchmark_memory": True}
        )


# ---------------------------------------------------------------------------
# Task 1: emit_invocation_configs
# ---------------------------------------------------------------------------


def test_emits_exactly_three_configs_in_order(tmp_path):
    source = _write_source(tmp_path)
    written = emit_invocation_configs(source, tmp_path / "invocations")
    assert [p.name for p in written] == [
        "config_e2_classification.yaml",
        "config_e2_timing.yaml",
        "config_e2_memory.yaml",
    ]
    assert all(p.exists() for p in written)


def test_variant_internals_match_d15_and_d16(tmp_path):
    source = _write_source(tmp_path)
    written = emit_invocation_configs(source, tmp_path / "invocations")
    internals = [yaml.safe_load(p.read_text())["internals"] for p in written]
    classification, timing, memory = internals

    # D-16: the ~11 MB h_q sidecar rides the classification run only.
    assert classification["log_all_observation_depths"] is True
    assert classification["benchmark_memory"] is False
    # D-15: the timing run carries neither perturbation.
    assert timing["log_all_observation_depths"] is False
    assert timing["benchmark_memory"] is False
    # D-15: memory instrumentation is its own run.
    assert memory["log_all_observation_depths"] is False
    assert memory["benchmark_memory"] is True


def test_no_variant_sets_both_internals_flags_true(tmp_path):
    source = _write_source(tmp_path)
    written = emit_invocation_configs(source, tmp_path / "invocations")
    for path in written:
        internals = yaml.safe_load(path.read_text())["internals"]
        assert not (
            internals["benchmark_memory"] and internals["log_all_observation_depths"]
        ), f"{path.name} sets both perturbing internals keys true"
    # And the same is true of the declarative table itself.
    for spec in E2_INVOCATION_VARIANTS:
        overrides = spec["internals"]
        assert not (
            overrides["benchmark_memory"] and overrides["log_all_observation_depths"]
        )


def test_variants_have_distinct_output_dirs(tmp_path):
    source = _write_source(tmp_path)
    written = emit_invocation_configs(source, tmp_path / "invocations")
    output_dirs = [
        yaml.safe_load(p.read_text())["paths"]["output_dir"] for p in written
    ]
    assert len(set(output_dirs)) == 3
    assert all(d != "/original/output_dir" for d in output_dirs)


def test_refuses_to_write_into_the_source_config_directory(tmp_path):
    source = _write_source(tmp_path)
    with pytest.raises(ValueError, match="inside the source config's own directory"):
        emit_invocation_configs(source, source.parent)


def test_refuses_to_write_under_the_source_config_directory(tmp_path):
    source = _write_source(tmp_path)
    with pytest.raises(ValueError, match="inside the source config's own directory"):
        emit_invocation_configs(source, source.parent / "nested" / "deeper")


def test_scope_sidecar_records_sha256_and_settings(tmp_path):
    source = _write_source(tmp_path)
    target = tmp_path / "invocations"
    emit_invocation_configs(source, target)
    record = json.loads((target / "e2_invocation_scope.json").read_text())

    expected_sha = hashlib.sha256(source.read_bytes()).hexdigest()
    assert record["source_config_sha256"] == expected_sha
    assert record["n"] == 3
    names = [v["name"] for v in record["variants"]]
    assert names == ["classification", "timing", "memory"]
    for variant in record["variants"]:
        assert set(variant["internals"]) == {
            "benchmark_memory",
            "log_all_observation_depths",
        }
        assert variant["output_dir"]
        assert variant["filename"].startswith("config_e2_")
    assert len({v["output_dir"] for v in record["variants"]}) == 3


def test_source_config_is_never_modified(tmp_path):
    source = _write_source(tmp_path)
    before = source.read_bytes()
    emit_invocation_configs(source, tmp_path / "invocations")
    assert source.read_bytes() == before


# ---------------------------------------------------------------------------
# Task 1: CLI surface
# ---------------------------------------------------------------------------


def test_help_lists_the_new_and_preexisting_extra_flags():
    help_text = build_arg_parser().format_help()
    for flag in (
        "--emit-invocation-configs",
        "--invocation-dir",
        "--config",
        "--emit-band-configs",
        "--band-seeds",
        "--band-dir",
        "--baseline-dir",
    ):
        assert flag in help_text


def test_help_states_the_operative_reason():
    help_text = build_arg_parser().format_help()
    assert "2.7" in help_text and "5.5" in help_text
    assert "11 MB" in help_text or "11MB" in help_text


@pytest.mark.parametrize(
    "extra,offender",
    [
        (["--check"], "--check"),
        (["--smoke"], "--smoke"),
        (["--force"], "--force"),
        (["--emit-band-configs", "--band-dir", "b"], "--emit-band-configs"),
    ],
)
def test_rejects_forbidden_flag_combinations(tmp_path, capsys, extra, offender):
    source = _write_source(tmp_path)
    argv = [
        "--emit-invocation-configs",
        "--invocation-dir",
        str(tmp_path / "inv"),
        "--config",
        str(source),
        *extra,
    ]
    with pytest.raises(SystemExit) as exc:
        main(argv)
    assert exc.value.code != 0
    err = capsys.readouterr().err
    assert "--emit-invocation-configs" in err
    assert offender in err


def test_requires_config_and_invocation_dir(tmp_path, capsys):
    with pytest.raises(SystemExit):
        main(["--emit-invocation-configs", "--invocation-dir", str(tmp_path / "inv")])
    assert "--config" in capsys.readouterr().err

    source = _write_source(tmp_path)
    with pytest.raises(SystemExit):
        main(["--emit-invocation-configs", "--config", str(source)])
    assert "--invocation-dir" in capsys.readouterr().err


def test_main_emits_configs_without_running_any_calibration(tmp_path):
    source = _write_source(tmp_path)
    target = tmp_path / "invocations"
    rc = main(
        [
            "--emit-invocation-configs",
            "--config",
            str(source),
            "--invocation-dir",
            str(target),
        ]
    )
    assert rc == 0
    assert (target / "config_e2_classification.yaml").exists()
    assert (target / "config_e2_timing.yaml").exists()
    assert (target / "config_e2_memory.yaml").exists()
    assert (target / "e2_invocation_scope.json").exists()


# ---------------------------------------------------------------------------
# Task 2: --check verdict folding (ruling A4)
# ---------------------------------------------------------------------------


def _passed(name: str) -> ComparisonReport:
    return ComparisonReport(
        passed=True,
        worst_cell=None,
        worst_rtol=0.0,
        n_mismatched_cells=0,
        message=f"{name} matched within tolerance",
    )


def _failed(name: str) -> ComparisonReport:
    return ComparisonReport(
        passed=False,
        worst_cell="cam0/x_m",
        worst_rtol=1e-3,
        n_mismatched_cells=4,
        message=f"{name} MISMATCH at 4 cells",
    )


def test_all_baselines_present_and_matching_exits_zero(tmp_path, capsys):
    reports = [
        (name, tmp_path / name, _passed(name)) for name in ("a.csv", "b.csv", "c.csv")
    ]
    assert _fold_check_reports(reports) == 0
    out = capsys.readouterr().out
    assert "matched within tolerance" in out
    assert "N/A" not in out


def test_missing_baseline_is_na_and_does_not_fail(tmp_path, capsys):
    reports = [
        ("camera_parameters.csv", tmp_path / "camera_parameters.csv", _passed("cp")),
        ("reprojection_residuals.csv", tmp_path / "reprojection_residuals.csv", None),
        ("reconstruction_errors.csv", tmp_path / "reconstruction_errors.csv", None),
    ]
    assert _fold_check_reports(reports) == 0
    out = capsys.readouterr().out
    assert out.count("N/A") == 2
    assert "reprojection_residuals.csv" in out
    assert "DATA-01b" in out


def test_present_and_differing_baseline_still_fails(tmp_path, capsys):
    reports = [
        ("camera_parameters.csv", tmp_path / "camera_parameters.csv", _failed("cp")),
        ("reprojection_residuals.csv", tmp_path / "reprojection_residuals.csv", None),
        ("reconstruction_errors.csv", tmp_path / "reconstruction_errors.csv", None),
    ]
    assert _fold_check_reports(reports) == 1
    assert "MISMATCH" in capsys.readouterr().out


def test_all_absent_is_vacuous_and_never_reads_as_a_pass(tmp_path, capsys):
    reports = [
        (name, tmp_path / name, None)
        for name in (
            "camera_parameters.csv",
            "reprojection_residuals.csv",
            "reconstruction_errors.csv",
        )
    ]
    assert _fold_check_reports(reports) != 0
    out = capsys.readouterr().out
    assert "vacuous" in out


def test_run_check_uses_the_present_guard_three_times():
    """`_run_check` must route every comparison through the N/A-guarded wrapper."""
    import inspect

    from experiments import e2_real_rig

    src = inspect.getsource(e2_real_rig._run_check)
    assert src.count("compare_experiment_csv_if_present(") == 3
    assert "compare_experiment_csv(" not in src.replace(
        "compare_experiment_csv_if_present(", ""
    )
    assert "resolve_baseline_dir(" in src
