"""Unit tests for `experiments/e2_real_rig.py`'s COV-07 seed-variant config
generator and its calibration-free CLI path (D-19.5-05, D-19.5-07 plan).

Every test here uses a small inline fixture config text -- never the real
Desktop production config -- so the suite has no external dependency and
never touches `C:/Users/tucke/Desktop/Aqua/AquaCal/release_calibration/`. No
test invokes `run_calibration` or performs a calibration.
"""

from __future__ import annotations

import json

import pytest
import yaml

from experiments._io import build_experiment_arg_parser
from experiments.e2_real_rig import (
    build_seed_variant_config,
    emit_seed_variant_configs,
    main,
)

# A fixture config carrying comments, blank lines, and a nested `paths:` block --
# mirrors the shape of the real production config without any real paths.
FIXTURE_CONFIG_NO_SEED = """\
# AquaCal configuration file
# Generated by 'aquacal init'

board:
  squares_x: 12
  squares_y: 9

cameras:
  - cam0
  - cam1

paths:
  intrinsic_videos:
    cam0: "/videos/intrinsics/cam0.avi"
    cam1: "/videos/intrinsics/cam1.avi"
  extrinsic_videos:
    cam0: "/videos/extrinsics/cam0.avi"
    cam1: "/videos/extrinsics/cam1.avi"
  output_dir: "/original/output_dir"

interface:
  n_air: 1.0
  n_water: 1.333
"""

FIXTURE_CONFIG_WITH_SEED = """\
# AquaCal configuration file
seed: 42

board:
  squares_x: 12

paths:
  output_dir: "/original/output_dir"
"""


class TestBuildSeedVariantConfig:
    def test_two_key_diff_no_seed_key(self):
        result = build_seed_variant_config(FIXTURE_CONFIG_NO_SEED, 43, "/tmp/x")
        source_lines = FIXTURE_CONFIG_NO_SEED.splitlines()
        result_lines = result.splitlines()

        # Exactly one new line (the inserted `seed:`), and every source line
        # is still present, unchanged, save for the output_dir line.
        assert len(result_lines) == len(source_lines) + 1

        source_non_output_lines = [
            line for line in source_lines if "output_dir:" not in line
        ]
        result_non_output_lines = [
            line
            for line in result_lines
            if "output_dir:" not in line and line != "seed: 43"
        ]
        assert source_non_output_lines == result_non_output_lines

        assert "seed: 43" in result_lines
        output_dir_lines = [line for line in result_lines if "output_dir:" in line]
        assert len(output_dir_lines) == 1
        assert '"/tmp/x"' in output_dir_lines[0]

    def test_no_seed_key_gains_exactly_one_line_and_parses(self):
        result = build_seed_variant_config(FIXTURE_CONFIG_NO_SEED, 43, "/tmp/x")
        assert len(result.splitlines()) == len(FIXTURE_CONFIG_NO_SEED.splitlines()) + 1
        parsed = yaml.safe_load(result)
        assert parsed["seed"] == 43
        assert parsed["paths"]["output_dir"] == "/tmp/x"

    def test_existing_seed_key_replaced_no_net_lines(self):
        result = build_seed_variant_config(FIXTURE_CONFIG_WITH_SEED, 43, "/tmp/x")
        assert len(result.splitlines()) == len(FIXTURE_CONFIG_WITH_SEED.splitlines())
        parsed = yaml.safe_load(result)
        assert parsed["seed"] == 43

    def test_all_source_comments_present_in_output(self):
        result = build_seed_variant_config(FIXTURE_CONFIG_NO_SEED, 43, "/tmp/x")
        source_comment_lines = [
            line
            for line in FIXTURE_CONFIG_NO_SEED.splitlines()
            if line.strip().startswith("#")
        ]
        result_lines = result.splitlines()
        for comment_line in source_comment_lines:
            assert comment_line in result_lines

    def test_emitted_variants_differ_only_in_seed_and_output_dir(self, tmp_path):
        source_path = tmp_path / "source" / "config.yaml"
        source_path.parent.mkdir(parents=True)
        source_path.write_text(FIXTURE_CONFIG_NO_SEED)

        band_dir = tmp_path / "band"
        paths = emit_seed_variant_configs(source_path, [42, 43, 44], band_dir)
        assert len(paths) == 3

        texts = {p: p.read_text() for p in paths}
        line_sets = {p: t.splitlines() for p, t in texts.items()}

        # Every variant has the same number of lines.
        lengths = {len(lines) for lines in line_sets.values()}
        assert len(lengths) == 1

        for i in range(next(iter(lengths))):
            values_at_line = {lines[i] for lines in line_sets.values()}
            if len(values_at_line) > 1:
                for line in values_at_line:
                    assert "seed:" in line or "output_dir:" in line


class TestEmitSeedVariantConfigsRefusesReleaseTree:
    def test_raises_when_band_dir_is_source_parent(self, tmp_path):
        source_path = tmp_path / "release" / "config.yaml"
        source_path.parent.mkdir(parents=True)
        source_path.write_text(FIXTURE_CONFIG_NO_SEED)

        with pytest.raises(ValueError, match="release tree|band_dir"):
            emit_seed_variant_configs(source_path, [42], source_path.parent)

    def test_raises_when_band_dir_is_nested_inside_source_parent(self, tmp_path):
        source_path = tmp_path / "release" / "config.yaml"
        source_path.parent.mkdir(parents=True)
        source_path.write_text(FIXTURE_CONFIG_NO_SEED)

        nested = source_path.parent / "band_subdir"
        with pytest.raises(ValueError, match="release tree|band_dir"):
            emit_seed_variant_configs(source_path, [42], nested)

    def test_fixture_configs_use_no_real_filesystem_paths(self):
        """Both inline fixture configs use placeholder paths only.

        This is the concrete form of "no test reads a path under
        C:/Users/tucke/Desktop": every path this file operates on is either a
        pytest `tmp_path` or one of the `/videos/...`, `/original/...`
        placeholder strings below -- never the real release tree.
        """
        for fixture_text in (FIXTURE_CONFIG_NO_SEED, FIXTURE_CONFIG_WITH_SEED):
            assert "tucke" not in fixture_text
            assert "Desktop" not in fixture_text


class TestCli:
    def test_help_lists_new_flags(self, capsys):
        with pytest.raises(SystemExit):
            main(["--help"])
        out = capsys.readouterr().out
        assert "--emit-band-configs" in out
        assert "--band-seeds" in out
        assert "--band-dir" in out

    def test_emit_band_configs_without_config_exits_nonzero(self, tmp_path, capsys):
        with pytest.raises(SystemExit) as exc_info:
            main(["--emit-band-configs", "--band-dir", str(tmp_path)])
        assert exc_info.value.code != 0
        err = capsys.readouterr().err
        assert "--config" in err

    def test_emit_band_configs_without_band_dir_exits_nonzero(self, tmp_path, capsys):
        config_path = tmp_path / "config.yaml"
        config_path.write_text(FIXTURE_CONFIG_NO_SEED)
        with pytest.raises(SystemExit) as exc_info:
            main(["--emit-band-configs", "--config", str(config_path)])
        assert exc_info.value.code != 0
        err = capsys.readouterr().err
        assert "--band-dir" in err

    def test_emit_band_configs_with_check_exits_nonzero(self, tmp_path):
        config_path = tmp_path / "config.yaml"
        config_path.write_text(FIXTURE_CONFIG_NO_SEED)
        with pytest.raises(SystemExit):
            main(
                [
                    "--emit-band-configs",
                    "--config",
                    str(config_path),
                    "--band-dir",
                    str(tmp_path / "band"),
                    "--check",
                ]
            )

    def test_emit_band_configs_with_smoke_exits_nonzero(self, tmp_path):
        config_path = tmp_path / "config.yaml"
        config_path.write_text(FIXTURE_CONFIG_NO_SEED)
        with pytest.raises(SystemExit):
            main(
                [
                    "--emit-band-configs",
                    "--config",
                    str(config_path),
                    "--band-dir",
                    str(tmp_path / "band"),
                    "--smoke",
                ]
            )

    def test_shared_five_flag_contract_unchanged(self):
        parser = build_experiment_arg_parser()
        options = sorted(
            a.option_strings[0] for a in parser._actions if a.option_strings
        )
        assert options == ["--check", "--force", "--out", "--seed", "--smoke"]


class TestEmitBandConfigsRun:
    def test_emits_three_variants_and_scope_file_no_calibration(self, tmp_path):
        config_path = tmp_path / "source" / "config.yaml"
        config_path.parent.mkdir(parents=True)
        config_path.write_text(FIXTURE_CONFIG_NO_SEED)
        band_dir = tmp_path / "band"

        exit_code = main(
            [
                "--emit-band-configs",
                "--config",
                str(config_path),
                "--band-seeds",
                "42,43,44",
                "--band-dir",
                str(band_dir),
            ]
        )
        assert exit_code == 0

        for seed in (42, 43, 44):
            assert (band_dir / f"config_seed{seed}.yaml").exists()
        scope_path = band_dir / "e2_band_scope.json"
        assert scope_path.exists()

        record = json.loads(scope_path.read_text())
        assert record["seeds"] == [42, 43, 44]
        assert record["n"] == 3
        assert "source_config_sha256" in record
        assert record["source_config"] == str(config_path.resolve())

    def test_no_calibration_import_reachable_from_emit_path(self):
        """`main` must not call `run_calibration` on the --emit-band-configs path.

        Asserted at the source level: `_run_emit_band_configs`'s own body never
        references `run_calibration`, and the emit path returns before any of
        `_run_smoke`/`_run_check`/`_run_full` (which do) is reached.
        """
        import inspect

        from experiments.e2_real_rig import _run_emit_band_configs

        source = inspect.getsource(_run_emit_band_configs)
        assert "run_calibration" not in source

    def test_scope_field_states_split_not_measurement_variance(self, tmp_path):
        config_path = tmp_path / "source" / "config.yaml"
        config_path.parent.mkdir(parents=True)
        config_path.write_text(FIXTURE_CONFIG_NO_SEED)
        band_dir = tmp_path / "band"

        main(
            [
                "--emit-band-configs",
                "--config",
                str(config_path),
                "--band-dir",
                str(band_dir),
            ]
        )
        record = json.loads((band_dir / "e2_band_scope.json").read_text())
        assert "split variance" in record["scope"]
        assert "NOT measurement variance" in record["scope"]

    def test_default_band_seeds_is_42_43_44(self, tmp_path):
        config_path = tmp_path / "source" / "config.yaml"
        config_path.parent.mkdir(parents=True)
        config_path.write_text(FIXTURE_CONFIG_NO_SEED)
        band_dir = tmp_path / "band"

        main(
            [
                "--emit-band-configs",
                "--config",
                str(config_path),
                "--band-dir",
                str(band_dir),
            ]
        )
        record = json.loads((band_dir / "e2_band_scope.json").read_text())
        assert record["seeds"] == [42, 43, 44]

    def test_variant_config_contents_readable_by_load_config(self, tmp_path):
        """A variant is a valid config text (parses and carries the right seed)."""
        config_path = tmp_path / "source" / "config.yaml"
        config_path.parent.mkdir(parents=True)
        config_path.write_text(FIXTURE_CONFIG_NO_SEED)
        band_dir = tmp_path / "band"

        main(
            [
                "--emit-band-configs",
                "--config",
                str(config_path),
                "--band-dir",
                str(band_dir),
            ]
        )
        variant = yaml.safe_load((band_dir / "config_seed43.yaml").read_text())
        assert variant["seed"] == 43
        assert "seed_43" in variant["paths"]["output_dir"]
